### PR TITLE
Fixed indent issue.

### PR DESCRIPTION
**Pull request by moorepants**

### CODE REVIEW

**Comment by moorepants** [comment]
Now getting this error:

```
+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/recipe_root_1485803715144/_t_env
+ /bin/bash -x -e /feedstock_root/build_artefacts/recipe_root_1485803715144/test_tmp/run_test.sh
+ bash test.sh
  File "<stdin>", line 1
    upload_or_check_non_existence /recipe_root conda-forge --channel=main || exit 1
                                                   ^
SyntaxError: invalid syntax
  File "<stdin>", line 3
    export CONDA_PY=35
                  ^
SyntaxError: invalid syntax
TESTS FAILED: yeadon-1.3.0-py27_0

./ci_support/run_docker_build.sh returned exit code 1
```

I'm guessing the feedstock needs to be rerendered.

**Comment by ocefpaf** [comment]
That indentation always existed. I guess it is something else :unamused:

**Comment by moorepants** [comment]
I'll close this. Any tips on what may be wrong are welcomed.

**Comment by ocefpaf** [comment]
> I'll close this. Any tips on what may be wrong are welcomed. investigating... Hold on...

**Pull request closed without merging**
